version: '3'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - PORT=8080
      - DATABASE_CONN=mongodb://localhost:27017/covid19-restaurants

  database:
    image: mongo
