version: '3'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_CONN=mongodb://database:27017/covid19-restaurants
    depends_on:
      - database

  database:
    image: mongo
